#ifndef __CONSTVALUE_H
#define __CONSTVALUE_H	

#include "stm32f10x.h"

extern const u8 ToBoot[4];
extern const u8 ToApp[4];
extern const u16 TabCRC[256];

#define USB_PROTOCOL_SIZE 6  // 55 aa 01 长度 命令码 ... 和校验 占6个字节
#define USB_ONE_PACKAGE_SEND_SIZE 64
#define USB_ONE_PACKAGE_REAL_DATA_SIZE (USB_ONE_PACKAGE_SEND_SIZE - USB_PROTOCOL_SIZE - 2)   //55 aa 01 长度 命令码 当前包数占2字节... 和校验 占6个字节
#define USB_RECV_MAX_PAGES_ONCE 40
#define USB_RECV_BYTES (USB_ONE_PACKAGE_REAL_DATA_SIZE * USB_RECV_MAX_PAGES_ONCE)  //用于定义存放数组的大小  40包数据
#define USB_RECV_OFFSET (USB_RECV_BYTES - FLASH_ADDR_APP_OFFSET)

#define FLAG_TO_BOOT 0
#define FLAG_TO_APP 1
#define FLASH_ADDR_UPDATE_FLAG 0x0803F800  //存放标志位
#define FLASH_ADDR_APP 	0x08010000  //App程序存放地址
#define FLASH_ADDR_APP_OFFSET 2048
#define FLASH_ADDR_BOOT	((uint32_t)0x08000000) 
#define FLASH_VTOR_OFFSET  ((uint32_t)0x10000)


enum FIRMWARE_UPDATE
{
	FIRMWARE_UPDATE_BOOT = 0,
	FIRMWARE_UPDATE_BOOT_PREPAR_OK,
	FIRMWARE_UPDATE_TOTAL_PACKAGES_AND_CRC,
	FIRMWARE_UPDATE_TOTAL_PACKAGES_AND_CRC_OK,
	FIRMWARE_UPDATE_NEXT_PACKAGE,
	FIRMWARE_UPDATE_FINISHED,
	FIRMWARE_UPDATE_UNSECUESSED
};

enum USB_CODE
{
    USB_CODE_ERROR = 0XF0,
};









#endif
